routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MainController@index')->name('main');

Route::resource('phone-book', 'PhoneBookController');
Route::resource('phone', 'PhoneController');

app/Models/Phone.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Phone extends Model
{
    protected $fillable = ['phone', 'phone_book_id'];

    public function phoneBook()
    {
        return $this->belongsTo(PhoneBook::class);
    }
}

app/Models/PhoneBook.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class PhoneBook extends Model
{
    protected $fillable = ['first_name', 'middle_name', 'last_name'];

    public function phones()
    {
        return $this->hasMany(Phone::class);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/MainController.php
<?php

namespace App\Http\Controllers;

use App\Models\PhoneBook;
use Illuminate\Http\Request;

class MainController extends Controller
{
    public function index(PhoneBook $phoneBook)
    {
        $phoneBooks = $phoneBook->with('phones')->get();

        return view('main', compact('phoneBooks'));
    }
}

app/Http/Controllers/PhoneBookController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\PhoneBook\StoreRequest;
use App\Http\Requests\PhoneBook\UpdateRequest;
use App\Models\Phone;
use App\Models\PhoneBook;
use Illuminate\Http\Request;
use DB;

class PhoneBookController extends Controller
{
    public function store(StoreRequest $storeRequest, PhoneBook $phoneBook, Phone $phone)
    {
        $phoneBook->fill($storeRequest->validated());
        $phone->fill($storeRequest->validated());

        DB::transaction(function () use ($phoneBook, $phone){
            $phoneBook->save();
            $phoneBook->phones()->save($phone);
        });

        return redirect()->back();
    }

    public function update(UpdateRequest $updateRequest, PhoneBook $phoneBook)
    {
        $phoneBook->fill($updateRequest->validated());

        $phoneBook->save();

        return redirect()->back();
    }

    public function destroy(PhoneBook $phoneBook)
    {
        $phoneBook->phones()->delete();
        $phoneBook->delete();

        return redirect()->back();
    }
}

app/Http/Controllers/PhoneController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Phone\StoreRequest;
use App\Http\Requests\Phone\UpdateRequest;
use App\Models\Phone;
use Illuminate\Http\Request;

class PhoneController extends Controller
{
    public function update(UpdateRequest $updateRequest, Phone $phone)
    {
        $phone->fill($updateRequest->validated());
        $phone->save();

        return redirect()->back();
    }

    public function store(StoreRequest $storeRequest, Phone $phone)
    {
        $phone->fill($storeRequest->validated());
        $phone->save();

        return redirect()->back();
    }

    public function destroy(Phone $phone)
    {
        $error = null;
        if($phone->where('phone_book_id', $phone->phone_book_id)->count() > 1){
            $phone->delete();
        }else{
            $error['last_phone'.$phone->id] = 'This number is not deleted, because it is the last number for the user.';
        }

        return redirect()->back()->withErrors($error);
    }
}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<!--[if IE 8]>
<html lang="en" class="ie8"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<head>
    <meta charset="utf-8"/>
    <title>:)</title>
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
<div class="container">
    <div class="py-5 text-center">
        <h2>Phone Book</h2>
    </div>

    <div class="row">
        @yield('content')
    </div>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
                integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
                crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
                integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
                crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
                integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
                crossorigin="anonymous"></script>

</body>
</html>

resources/views/main.blade.php
@extends('layouts.app')

@section('content')
    <div class="col-md-4">
        <form action="{{route('phone-book.store')}}" method="POST">
            @csrf
            <div class="form-group">
                <label for="exampleInputEmail1">First name</label>
                <input type="text" class="form-control" name="first_name" placeholder="Peter">
            </div>
            @if($errors->has('first_name'))
                <div class="invalid-feedback" style="display: block;">
                    {{$errors->first('first_name')}}
                </div>
            @endif
            <div class="form-group">
                <label for="exampleInputPassword1">Middle name</label>
                <input type="text" class="form-control" name="middle_name" placeholder="Jone">
            </div>
            @if($errors->has('middle_name'))
                <div class="invalid-feedback" style="display: block;">
                    {{$errors->first('middle_name')}}
                </div>
            @endif
            <div class="form-group">
                <label for="exampleInputPassword1">Last name</label>
                <input type="text" class="form-control" name="last_name" placeholder="White">
            </div>
            @if($errors->has('last_name'))
                <div class="invalid-feedback" style="display: block;">
                    {{$errors->first('last_name')}}
                </div>
            @endif
            <div class="form-group">
                <label for="exampleInputPassword1">Phone</label>
                <input type="number" class="form-control" name="phone" placeholder="380662243712">
            </div>
            @if($errors->has('phone'))
                <div class="invalid-feedback" style="display: block;">
                    {{$errors->first('phone')}}
                </div>
            @endif
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
    <div class="col-md-8">
        <div class="row">
            @foreach($phoneBooks as $phoneBook)
                <div class="col-md-12 pb-5">
                    <div>
                        <b>{{$phoneBook->first_name}} {{ $phoneBook->middle_name }} {{ $phoneBook->last_name }}</b>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal{{$phoneBook->id}}">
                            edit user
                        </button>
                        <form action="{{route('phone-book.destroy', $phoneBook->id)}}" method="POST" style="display: inline-block;">
                            @csrf
                            @method('DELETE')
                            <button class="btn btn-danger" type="submit">delete user</button>
                        </form>
                    </div>

                    <div class="modal fade" id="exampleModal{{$phoneBook->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <form action="{{route('phone-book.update', $phoneBook->id)}}" method="POST">
                                    @csrf
                                    @method('PUT')
                                    <div class="modal-body">
                                        <div class="form-group">
                                            <label for="exampleInputEmail1">First name</label>
                                            <input type="text" class="form-control" name="first_name" value="{{$phoneBook->first_name}}" placeholder="Peter">
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputPassword1">Middle name</label>
                                            <input type="text" class="form-control" name="middle_name" value="{{$phoneBook->middle_name}}" placeholder="Jone">
                                        </div>
                                        <div class="form-group">
                                            <label for="exampleInputPassword1">Last name</label>
                                            <input type="text" class="form-control" name="last_name" value="{{$phoneBook->last_name}}" placeholder="White">
                                        </div>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                        <button type="submit" class="btn btn-primary">Save</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <ul class="list-group">
                        @foreach($phoneBook->phones as $phone)
                            <li class="list-group-item">
                                {{$phone->phone}}

                                <form action="{{route('phone.destroy', $phone->id)}}" class="float-right" method="POST" style="display: inline-block;">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger" type="submit">delete number</button>
                                </form>

                                <button type="button" class="btn btn-primary float-right" data-toggle="modal" data-target="#exampleModal{{$phoneBook->id}}{{$phone->id}}">
                                    edit phone
                                </button>


                                @if($errors->has('last_phone'.$phone->id))
                                    <div class="invalid-feedback" style="display: block;">
                                        {{$errors->first('last_phone'.$phone->id)}}
                                    </div>
                                @endif
                            </li>
                            <div class="modal fade" id="exampleModal{{$phoneBook->id}}{{$phone->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <form action="{{route('phone.update', $phone->id)}}" method="POST">
                                            @csrf
                                            @method('PUT')
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Изменить номер</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <div class="modal-body">
                                                <div class="form-group">
                                                    <label for="exampleInputPassword1">Phone</label>
                                                    <input type="number" class="form-control" name="phone" value="{{$phone->phone}}" placeholder="380662243712">
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                <button type="submit" class="btn btn-primary">Save</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                        <li class="list-group-item">
                            Create New Phone for user <b>{{$phoneBook->first_name}}</b>
                            <form action="{{route('phone.store')}}" method="POST">
                                @csrf
                                <input type="number" name="phone_book_id" value="{{$phoneBook->id}}" style="display: none;">
                                <div class="form-group">
                                    <input type="number" class="form-control" name="phone" placeholder="380662243712">
                                </div>
                                <button type="submit" class="btn btn-primary">Create</button>
                            </form>
                            @if($errors->has('phone'))
                                <div class="invalid-feedback" style="display: block;">
                                    {{$errors->first('phone')}}
                                </div>
                            @endif
                        </li>
                    </ul>
                </div>
            @endforeach
        </div>
    </div>
@endsection